name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: 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
          owner: severt-webclass
